name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run 
        required: true 
        type: choice 
        default: all 
        options: 
          - all
          - contact_us  
          - home_page   

jobs:
  run-tests:
    runs-on: ubuntu-latest  
    name: Tests
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4
      - name: Set up Python environment  
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          if [[ "${{ github.event.inputs.deployment_target }}" == "all" ]]; then
            pytest tests/ 
          elif [[ "${{ github.event.inputs.deployment_target }}" == "contact_us" ]]; then
            pytest tests/test_contactus.py  # Запускає тести тільки для Contact Us
          elif [[ "${{ github.event.inputs.deployment_target }}" == "home_page" ]]; then
            pytest tests/test_homepage.py  # Запускає тести тільки для домашньої сторінки
          fi
